### PR TITLE
Lab #1 review

### PR DESCRIPTION
**Pull request by damhuman**

### CODE REVIEW

**Comment by Futurer** [comment]
Project: https://github.com/SwiftyJSON/SwiftyJSON

wrong link path generation, for example:
file:///Tests/SwiftJSONTests//SubscriptTests.html

**Comment by damhuman** [comment]
Fixed this problem

**Comment by Futurer** [comment]
wrong link generation

generated link: file:///Tests/SwiftJSONTests/ArrayTests.html
real path to file:file:///home/user/Downloads/Dasiuk-2/Tests/SwiftJSONTests/ArrayTests.html

**Comment by damhuman** [comment]
@Futurer, hope I`ve resolved this issue :)

**Pull request merged**
